### PR TITLE
Fix race conditions in TestLocalMsgProtocol.

### LINKED ISSUE #1782: Fix race conditions in TestLocalMsgProtocol
TestLocalMsgProtocol has some logic that looks like this:

    synchronized (someLockObject) {
        someFlag = true;
        someLockObject.notifyAll();
    }

    someBlockingFunctionThatMakesFlagActuallyTrue();

That's clearly a race condition, as the condition flag is set before the condition is actually true. If we're relying on timing here, we're giving ourselves a false sense of security.

Additionally, TestLocalMsgProtocol uses wait-loops to wait for connections to be opened. However, it also opens those connections on separate threads, so the wait-loops are unnecessary because we can just `join` on the thread that creates the connection.

### PR DESCRIPTION
**Pull request by TimAbraldes**
TestLocalMsgProtocol has some logic that looks like this:

    synchronized (someLockObject) {
        someFlag = true;
        someLockObject.notifyAll();
    }

    someBlockingFunctionThatMakesFlagActuallyTrue();

That's clearly a race condition, as the condition flag is set before the
condition is actually true. If we're relying on timing here, we're
giving ourselves a false sense of security.

Additionally, TestLocalMsgProtocol uses wait-loops to wait for
connections to be opened. However, it also opens those connections on
separate threads, so the wait-loops are unnecessary because we can just
`join` on the thread that creates the connection.

Fixes #1782

### CODE REVIEW

File: tests/org/mozilla/io/TestLocalMsgProtocol.java [hunk 1]
```diff
@@ -353,26 +309,13 @@ public void test(TestHarness th) {
...
-            synchronized (openLock) {
-                while (!serverAcceptAndOpenCalled) {
-                    openLock.wait();
-                }
-            }
-            Thread clientThread = new ThreadClient();
+            Thread clientThread = new ThreadClientCreate();
             clientThread.start();
-            serverCreateThread.join();
             serverAcceptAndOpenThread.join();
```
Comment (marco-c) [inline tests/org/mozilla/io/TestLocalMsgProtocol.java]: Scenario 1 was:
1) Server creates a localmsg server
2) Server calls acceptAndOpen
3) Client opens a localmsg server

With this change, 3 could happen before 2.

File: tests/org/mozilla/io/TestLocalMsgProtocol.java [hunk 2]
```diff
@@ -380,24 +323,11 @@ public void test(TestHarness th) {
...
-                    openLock.wait();
-                }
-            }
+            serverCreateThread.join();
             clientThread.start();
-            synchronized (openLock) {
-                while (!clientCreated) {
-                    openLock.wait();
-                }
-            }
```
Comment (marco-c) [inline tests/org/mozilla/io/TestLocalMsgProtocol.java]: Scenario 2 was:
1) Server creates a localmsg server
2) Client opens a localmsg server
3) Server calls acceptAndOpen

With this change, 3 could happen before 2.

File: tests/org/mozilla/io/TestLocalMsgProtocol.java [hunk 3]
```diff
@@ -405,24 +335,11 @@ public void test(TestHarness th) {
...
-            synchronized (openLock) {
-                while (!serverCreated) {
-                    openLock.wait();
-                }
-            }
-            serverAcceptAndOpenThread.start();
             serverCreateThread.join();
+            serverAcceptAndOpenThread.start();
             serverAcceptAndOpenThread.join();
             clientThread.join();
```
Comment (marco-c) [inline tests/org/mozilla/io/TestLocalMsgProtocol.java]: Scenario 3 was:
1) Client opens a localmsg server
2) Server creates a localmsg server
3) Server calls acceptAndOpen

With this change, 2 could happen before 1 and 3 could happen before 1.

**Comment by marco-c** [comment]
> That's clearly a race condition, as the condition flag is set before the
condition is actually true. If we're relying on timing here, we're
giving ourselves a false sense of security.

> Additionally, TestLocalMsgProtocol uses wait-loops to wait for
connections to be opened. However, it also opens those connections on
separate threads, so the wait-loops are unnecessary because we can just
join on the thread that creates the connection.

The test isn't very well documented, but there was a reason why I wrote it that way.
The simplest and probably best way to fix the race conditions is to use custom natives
for synchronization.

File: tests/org/mozilla/io/TestLocalMsgProtocol.java (hunk 1 above)
Comment (TimAbraldes) [inline tests/org/mozilla/io/TestLocalMsgProtocol.java]: > Scenario 1 was:
> 1) Server creates a localmsg server
> 2) Server calls acceptAndOpen
> 3) Client opens a localmsg server
>
> With this change, 3 could happen before 2.

Even without this change, 3 could happen before 2.

File: tests/org/mozilla/io/TestLocalMsgProtocol.java (hunk 2 above)
Comment (TimAbraldes) [inline tests/org/mozilla/io/TestLocalMsgProtocol.java]: > Scenario 2 was:
> 1) Server creates a localmsg server
> 2) Client opens a localmsg server
> 3) Server calls acceptAndOpen
>
> With this change, 3 could happen before 2.

Even without this change, 3 could happen before 2.

File: tests/org/mozilla/io/TestLocalMsgProtocol.java (hunk 3 above)
Comment (TimAbraldes) [inline tests/org/mozilla/io/TestLocalMsgProtocol.java]: > Scenario 3 was:
> 1) Client opens a localmsg server
> 2) Server creates a localmsg server
> 3) Server calls acceptAndOpen
>
> With this change, 2 could happen before 1 and 3 could happen before 1.

Even without this change, those outcomes are possible.

**Comment by TimAbraldes** [comment]
I'll update the patch now that I have a better understanding of what the test is intending to accomplish:
  1. I'll add documentation for each case based on the "scenario" comments you wrote
  2. I'll add `Thread.sleep` calls where appropriate to hopefully mostly ensure that events happen in the order we want them to

**Comment by marco-c** [comment]
> I'll add Thread.sleep calls where appropriate to hopefully mostly ensure that events happen in the order we want them to

Using custom natives for synchronization would actually fix the race conditions, but I'm OK with this workaround.

**Comment by marco-c** [comment]
> I'll add documentation for each case based on the "scenario" comments you wrote

The scarce documentation was in the *th.check* calls, for example: `th.check(true, "Server create, server accept and open, client open");`.

File: tests/org/mozilla/io/TestLocalMsgProtocol.java (hunk 1 above)
Comment (marco-c) [inline tests/org/mozilla/io/TestLocalMsgProtocol.java]: Yes, in general it could, but it doesn't with the way the scheduler works now. It's definitely a weak assumption, so it's great you're fixing it.

**Comment by TimAbraldes** [comment]
Updated: I think all review comments are now addressed
